### ISSUE TITLE
Some improvements for presentation

### ISSUE THREAD

**Issue by PhuongPhg** [PhuongPhg/medical-management-website#60]
- [x] Demo as fast as robbery -> Change speed
- [x] Emphasize on what tto manage (What data is that? Tracking what?) -> Pay attention on problems
- [x] Split motivation and objective
- [ ] Split objective to general and detail
- General: Manage, help doctor better
- Detail: the original motivation
- [x] UC: split smaller (into 3)
- [x] System architecture: 
- Make clear about server-side and client-side (ReactJS not React :))
- Overall figure in both sides 
- Show figma example
- [ ] Add conclusion
- [ ] More text on "Future" slide
- [ ] Q&A: What make it different with the old system

**Comment by chalalala** [comment]
I'm thinking of removing Figma from the presentation as due to Dr Son, if we include it in the Client-side part, then it must appear somewhere in the System Architecture as well, then we will have to redraw the figure.
